apiVersion: v1
appVersion: "0.1.0"
description: A Helm chart for Kubernetes
name: helloworld
version: 2.0.0

home: https://paulczar.github.io/charts
maintainers:
  - name: paulczar
    email: paul@paulcz.net
